name: Deploy Next.js site to Pages

on:
  push:
    branches: ['monorepo']

  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: 'pages'
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          # --- Caching for pnpm with setup-node ---
          cache: 'pnpm'

      - name: Setup Pages
        uses: actions/configure-pages@v5

      - name: Install dependencies
        # Use pnpm install --frozen-lockfile for deterministic install
        run: pnpm install --frozen-lockfile

      - name: Build with Next.js (Production Mode)
        run: pnpm run build
        env:
          NODE_ENV: production

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./out

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
